cd "../Morphology"
../../CompileFST/CompileFST.sh "Morphology.foma"
cd "../Segmentation"
../../CompileFST/CompileFST.sh "Segmentation.foma"
cd "../ExtendedSegmentation"
../../CompileFST/CompileFST.sh "ExtendedSegmentation.foma"
